### ISSUE TITLE
enter your word and explanation

### ISSUE THREAD

**Issue by annadragan** [annadragan/capstone-project#1]
### **Value** Proposition
**As a** user 
**I need to** enter new words and to write down texts (explanations) or example sentences
**to be able** to memorise this words and to have explanations of them (and/or examples of usage)

Step 2:
### **Description:**

<img src="https://user-images.githubusercontent.com/98175494/161141677-ef77789e-fe5a-4ba8-8a4b-e599c28622ab.png" alt="create form" width="300">

<img src="https://user-images.githubusercontent.com/98175494/161141091-7bcc1300-2b0d-4953-9521-e2eff1ecb4db.png" alt="card list" width="500">

### **Acceptance** Criteria
- [x] App has three input fields
- [x] App has a add button
- [x] Empty input or only whitespace does not submit
- [x] Disable submit if input is empty
- [x] Whitespaces in the input are trimmed on submit
- [x] Text in the first input has a max length of 20 characters
- [x] Text in the second input has a max length of 80 characters
- [x] Text in the third input has a max length of 200 characters
- [x] After completing the form and submit the user should be redirected to list of cards and see the new card on the card list
- [x]  By clicking on the create button every input field should reset
- [x] A user have a button with plus icon on the vocabulary cards page
- [x] By clicking the button with plus icon the create form page should open

### **Tasks**

- [x] Create branch `create-form`
- [x] Create three input fields
- [x] Create a button to add
- [x] Create a path to new page where cards are saved (implement react router and button functionality)
- [x] Implement plus-icon-button function to navigate to create form page
- [x] Component w/ storybook and test
- [x] Create function to save form-inputs
- [x] Check accessibility
- [x] Test on mobile device / different browser
