### ISSUE TITLE
search-bar

### ISSUE THREAD

**Issue by annadragan** [annadragan/capstone-project#10]
### **Value of Proposition**
**As a user**
**I need to have** a search bar on the Archive Page
**to be able to** find words I want to repeat more faster

### Description
<img src="https://user-images.githubusercontent.com/98175494/159998051-1b9003b3-5990-4609-9ad9-395a2876b6f4.png" alt="picture of user story - search-bar" width="300">

### Acceptance Criteria
- [x] I can successfully search for words I want to repeat

### Tasks
- [x] add a search bar and search logic to the Archive Page
- [x] Check accessibility
- [x] Test on mobile portrait/landscape screen
