### ISSUE TITLE
navigation

### ISSUE THREAD

**Issue by annadragan** [annadragan/capstone-project#12]
### **Value Proposition**

**As a user**
**I need to** have a navigation to cards, archive, quotes and stories pages and to see a navigation bar on every side
**to be able to** navigate conveniently between those pages

### Description:

<img src="https://user-images.githubusercontent.com/98175494/160004864-4d16e0c8-da03-4f00-aa9f-50d3438ec73f.png" alt="navigation" width="300">

### Acceptance criteria

- [ ] A navigation is implemented with React Router
- [ ] Navigate happened by clicking on the icon in navigation
- [ ] One icon leads to created cards
- [ ] One icon leads to bookmarked cards(archive)
- [ ] One icon leads to stories
- [ ] One icon leads to quotes
- [ ] Navigation should be displayed at the bottom of the viewport
- [ ] Navigation should always be visible for user
- [ ] Should have active and inactive states
- [ ] Depending on the page the user is on that page gets disabled in the menu

### Tasks

- [ ] Create branch `navigation`
- [ ] Build navigation component
- [ ] Create navigation/routing with React Route
- [ ] Build navigation bar with three icons
- [ ] Create pages: cards, archive, quotes and stories
- [ ] Add pages and navigation to the App
- [ ] Build navigation logic between pages
