### ISSUE TITLE
plus button

### ISSUE THREAD

**Issue by annadragan** [annadragan/capstone-project#13]
### **Value** Proposition
**As a** user 
**I need to** have a button to switch to my create form
**to be able** to create there a new words

### **Description:**

<img src="https://user-images.githubusercontent.com/98175494/160122851-6814d80e-8813-4664-af95-a2ea56603fe4.png" alt="card list" width="500">

### **Acceptance** Criteria
- [ ] A user have a button with plus icon
- [ ] By clicking the button the create form page should open

### **Tasks**

- [ ] Create branch `create-button`
- [ ] Implement plus icon button function to navigate to create form page
- [ ] Component w/ storybook and test
- [ ] Test on mobile device / different browser
