### ISSUE TITLE
confirm-delete

### ISSUE THREAD

**Issue by annadragan** [annadragan/capstone-project#18]
### **Value Proposition**

**As a user**
**I need to** get a confirm message on clicking delete button
**to be able to** doublecheck my choice. 

### Description:
<img src="https://user-images.githubusercontent.com/98175494/161518743-34abe76f-f5a4-41eb-be12-bb08bfe46ba6.png" alt="pop-up" width="300">

### Acceptance Criteria
- [x] confirm the delete choice in a pop-up window after clicking delete button

### Tasks
- [x]  create branch "confirm-delete"
- [x]  implement confirm-delete functionality
- [x]  Add/update storybook  and tests
- [x]  check in other browser
