### ISSUE TITLE
arrow-button

### ISSUE THREAD

**Issue by annadragan** [annadragan/capstone-project#19]
### **Value of Proposition**
**As a user**
**I need to have** an arrow button
**to be able to** navigate to the top of my page

### Description
<img src="https://user-images.githubusercontent.com/98175494/161524411-21eec12f-331c-4d18-8ffc-42688221e28f.png" alt="picture of user story - search-bar" width="300">

### Acceptance Criteria
- [x] by clicking on the arrow button on the bottom of vocabulary page it navigates to the top

### Tasks
- [x] create 'to the top' button and logic 
- [x] implement it at all card-pages
- [x] update with storybook and specs
- [x] test on different devices/browsers
