### ISSUE TITLE
Code refactoring

### ISSUE THREAD

**Issue by annadragan** [annadragan/capstone-project#2]
### Value Proposition
**As a Developer**
**I need** an App with clean code
**to be able** to maintain the app more easily

### Description:

**Code refactoring**

### Acceptance Criteria
- [x]  The length of the code is reduced and the code is more efficient

### Tasks
 
- [x] look for unnecessary code
- [x] update tests and stories
- [x] improve accessibility if needed
- [x] refactor components if needed
- [x] check that code is semantically correct 
- [x] test on  different browsers
