### ISSUE TITLE
photo upload

### ISSUE THREAD

**Issue by annadragan** [annadragan/capstone-project#22]
**As a user**
**I need to** have form to add an image and a description
**to be able to** visually support my cultural experience and learnings

### Description
<img src="https://user-images.githubusercontent.com/98175494/162988281-89dcf62b-789d-4bd6-bcca-e785f94f88ef.png" alt="photoUpload" width="300">

**Acceptance Criteria**
 
- [x] A form with the photo upload and one input field for the description
- [x] Uploading a picture should be possible
- [x]  Photos are formatted to a specific size
- [x] The user see a progress bar when uploading a photo
- [x] The image is optional 
- [x] The form doesn't submit  without input
- [x] Form has a submit button
- [x] Disable submit if input is empty
- [x]  Whitespaces in the input are trimmed on submit
- [x]  Text in the input has a max length of 300 characters
- [x]  After completing the form and submit the user should be redirected to list of tradition-cards and see the new card with image and description on the card list

**Tasks**
- [x] create 'photo-upload' branch
- [x] add one input field for description, a space with icon for photo upload and a save button
- [x] install cloudinary, axios
- [x] implement photo upload functionality
- [x] update with storybook and specs
- [x] test on different devices/browsers
