### ISSUE TITLE
add-tradition

### ISSUE THREAD

**Issue by annadragan** [annadragan/capstone-project#24]
### **Value of Proposition**
**As a user**
**I need to have** a form
**to be able to** to write about german tradition there

### Description
<img src="https://user-images.githubusercontent.com/98175494/162717708-57038f1f-fac3-4f48-8c38-7ddbdc6bb58d.png" alt="form-traditions" width="300">

### Acceptance Criteria
- [x] there is a form with two input fields and a save button

### Tasks
- [x] create 'traditions-form' branch
- [ ] add input fields and a save button
- [x] update with storybook and specs
- [x] test on different devices/browsers
