### ISSUE TITLE
delete tradition with confirmation

### ISSUE THREAD

**Issue by annadragan** [annadragan/capstone-project#25]
**As a user**
**I need to** delete my notes about german traditions
**in order to** to keep my tradition story page up to date

### Description
<img src="https://user-images.githubusercontent.com/98175494/163167943-c2d55e3f-269e-48a8-aa2f-f4be3f5e4072.png" alt="photoUpload" width="300">

**Acceptance Criteria**
 
- [x] Each card should  have an delete button with icon
- [x] after clicking the delete button a delete confirmation request will appear
- [x] confirm the delete choice in a pop-up window after clicking delete button

**Tasks**

- [x]  Create branch` delete`
- [x]  Create a delete button
- [x]  implement confirm-delete functionality and delete confirm request
- [x]  Add/update storybook  and tests
- [x]  check in other browser
