### ISSUE TITLE
toggle-traditions

### ISSUE THREAD

**Issue by annadragan** [annadragan/capstone-project#26]
**As a user**
**I want to** show/hide the description and name of the tradition
**in order** to see more/less details about the tradition when I want it

### Description

<img src="https://user-images.githubusercontent.com/98175494/163387259-0631dde8-792b-49a7-9170-d3f2b8e52e70.png" alt="toggle-traditions" width="300">

**Acceptance Criteria**

- [x]  the description of the tradition toggles when button is clicked
- [x]  a card expand and shrink alternately on a click 

**Tasks**

- [x]  create branch `toggle`
- [x]  create button "show/ hide explanation"
- [x]  update App with component and logic
- [x]  test on different devices/browsers
