### ISSUE TITLE
extra-input

### ISSUE THREAD

**Issue by annadragan** [annadragan/capstone-project#28]
### Value Proposition
**As a User**
**I need** to have one more input field
**to be able to** to give the tradition a title

### Description:

<img src="https://user-images.githubusercontent.com/98175494/163169716-df1031be-bcb2-44d6-9dcf-f13d24549959.png" alt="extra-input" width="300">

### Acceptance Criteria
- [x]  the ImageForm hat extra space for the title of the tradition

### Tasks
 
- [x] create one more input field
- [x] update the order of all inputs at ImageForm
- [x] update with storybook and specs
- [x] test on different devices/browsers
