### ISSUE TITLE
bookmark a card

### ISSUE THREAD

**Issue by annadragan** [annadragan/capstone-project#3]
### Value Proposition
**As a user**
**I need to** bookmark cards with words I already remember 
**so I have** a quick overview about my study progress and can separate them from words I still have to practice

Step 5:
### Description:

<img src="https://user-images.githubusercontent.com/98175494/160299002-56c4a8b0-991e-41f3-8d83-36ac0e2ba6c8.png" alt="bookmarked" width="600">

### Acceptance Criteria
- [x] Every vocabulary card has a bookmark button (with an icon) in upper right corner 
- [x] When the icon is clicked the bookmark is toggled
- [x] When the card is bookmarked it will be moved to another page
- [x] There is a navigation between vocabulary cards page and bookmarked/archive page 
- [x] Navigate happened by clicking on the icon in navigation
- [x] One icon leads to vocabulary cards page
- [x] One icon leads to bookmarked cards/archive page
- [x]  Depending on the page the user is on that page gets disabled in the menu

### Tasks
- [x]  Create branch `bookmark`
- [x]  Create a button to toggle
- [x]  Build navigation bar with two icons
- [x]  Create navigation/routing to the bookmarked/ archive page (React Router)
- [x]  Build navigation logic between pages
- [x]  Update App storybook and test
- [x]  Test on mobile device / different browser (Chrom, Safari, Firefox)
