### ISSUE TITLE
homepage

### ISSUE THREAD

**Issue by annadragan** [annadragan/capstone-project#31]
### Value Proposition
**As a User**
**I need** to have a home page
**to see** what this App is about

### Description:

<img src="https://user-images.githubusercontent.com/98175494/163873581-98c36bc6-9929-4a90-95e1-6307cf266104.png" alt="homepage" width="300">

### Acceptance Criteria
- [x]  there is a home page with a logo

### Tasks
 
- [x] expand the navigation 
- [x] create a logo
- [x] add an animation
- [x] test on different devices/browsers
