### ISSUE TITLE
delete card

### ISSUE THREAD

**Issue by annadragan** [annadragan/capstone-project#4]
### **Value Proposition**
**As a user**
**I want to be able** to delete unnecessary cards 
**in order to** clean up my vocabulary book 

Step 4:
### Description:

<img src="https://user-images.githubusercontent.com/98175494/160297658-9aaa2981-15e5-49bf-a0bc-3c85c3dd3c97.png" alt="delete" width="300">

### **Acceptance criteria**

- [x] Delete button deletes card on click

### Tasks

- [x] Create branch `delete-card`
- [x] Implement delete function with delete icon
- [x] Testing
