### ISSUE TITLE
local storage

### ISSUE THREAD

**Issue by annadragan** [annadragan/capstone-project#5]
### **Value Proposition**

**As a user**
**I need to** save my words and explanations
**so I can** still see and use them after closing and reopening the app

Step 3:
### Description:
Add local storage to save the cards information when the app is reloaded or reopened after closing. The data will be stored in the local storage.

### **Acceptance criteria**

- [x] Cards persist when the app is reopened
- [x] After reloading the app, the new word /explanation should still be displayed in the list of cards

### Tasks

- [x] Create branch `local-storage`
- [x] Implement local storage function
