### ISSUE TITLE
edit card

### ISSUE THREAD

**Issue by annadragan** [annadragan/capstone-project#6]
### **Value Proposition**
**As a user**
**I want** to be able to change/edit the content of my cards (or eliminate mistakes from there)
**in order to** keep my vocabulary cards up to date

### Description:

<img src="https://user-images.githubusercontent.com/98175494/159921492-021f7674-dd37-4eef-9ca4-b96982facc8b.png" alt="Picture of User Story xx" width="300">

### Acceptance Criteria
- [x]  A button to edit a card is shown on every single card
- [x]  Button has the functionality to edit a card
- [x]  The user can change all information on the card
- [x]  By clicking the save button the user gets back to the vocabulary cards page

### Tasks

- [x]  Add an edit button with icon to cards
- [x]  Add an functionality to edit the card
- [x]  Testing
