### ISSUE TITLE
idiomatic expressions

### ISSUE THREAD

**Issue by annadragan** [annadragan/capstone-project#8]
### **Value Proposition**
**As a user**
**I want to be able** to see a idiomatic expression
**in order to** boost my conversational language skills and to communicate better

### Description:

<img src="https://user-images.githubusercontent.com/98175494/159942492-b1f78675-1530-494f-aae8-14a2aafcbe71.png" alt="Picture of User Story xx" width="300">

### Acceptance criteria
- [x] phrase changes when the button 'next' clicked
- [x] there is a new page in the navigation for idiomatic expressions
- [x] wenn clicking the button new one phrase appears 
- [x] one phrase appears also after the page reload 

### Tasks
- [x]  create feature branch `idiomatic-expressions`
- [x] prepare data.js with idiomatic expressions (phrase + meaning)
- [x] implement data.js
