### ISSUE TITLE
card-list with mock data

### ISSUE THREAD

**Issue by annadragan** [annadragan/capstone-project#9]
### **Value** Proposition
**As a** user 
**I need to** have cards with new words 
**to be able** to see them and work with them later 

Step 1:
### **Description:**

<img src="https://user-images.githubusercontent.com/98175494/159955888-e7a8660f-eb67-4bbc-84d2-fe38d9679b8e.png" alt="picture of user story - card list" width="300">

### **Acceptance** Criteria
- [x] A user have a list of example cards with words and explanations to it
- [x] The list is scrollable

### **Tasks**

- [x] Create branch `cards`
- [x] Prepare some example mock data (array) for card list
- [x] Map over this array
- [x] Component w/ storybook and test
- [x] Test on mobile device / different browser
